import { z } from "zod";
import type { MeterSphereClient } from "../client.js";

const stepSchema = z.object({
  num: z.number().optional(),
  desc: z.string().optional(),
  expected: z.string().optional(),
});

export const createFunctionalModuleInputSchema = {
  projectId: z.string().optional().describe("Project ID; uses MS_PROJECT_ID when omitted"),
  name: z.string().optional().describe("Module name when not using modulePath"),
  parentId: z.string().optional(),
  modulePath: z.string().optional().describe("Path like 登录/短信登录; creates missing nodes"),
};

export const createFunctionalModuleTool = {
  name: "create_functional_module",
  description: "Create a functional case module, optionally by modulePath.",
  inputSchema: createFunctionalModuleInputSchema,
  handler: async (client: MeterSphereClient, args: Record<string, unknown>) => {
    const result = await client.createFunctionalModule(args as Parameters<MeterSphereClient["createFunctionalModule"]>[0]);
    return { content: [{ type: "text" as const, text: JSON.stringify(result, null, 2) }] };
  },
};

export const createFunctionalCaseInputSchema = {
  projectId: z.string().optional(),
  moduleId: z.string().optional(),
  modulePath: z.string().optional(),
  templateId: z.string().optional(),
  name: z.string(),
  priority: z.string().optional(),
  tags: z.array(z.string()).optional(),
  prerequisite: z.string().optional(),
  description: z.string().optional(),
  steps: z.array(stepSchema).optional(),
};

export const createFunctionalCaseTool = {
  name: "create_functional_case",
  description: "Create a single functional test case generated by the agent.",
  inputSchema: createFunctionalCaseInputSchema,
  handler: async (client: MeterSphereClient, args: Record<string, unknown>) => {
    const result = await client.createFunctionalCase(args);
    return { content: [{ type: "text" as const, text: JSON.stringify(result, null, 2) }] };
  },
};

export const batchCreateFunctionalCasesInputSchema = {
  projectId: z.string().optional(),
  moduleId: z.string().optional(),
  modulePath: z.string().optional(),
  templateId: z.string().optional(),
  failFast: z.boolean().optional(),
  cases: z
    .array(
      z.object({
        name: z.string(),
        priority: z.string().optional(),
        tags: z.array(z.string()).optional(),
        prerequisite: z.string().optional(),
        description: z.string().optional(),
        steps: z.array(stepSchema).optional(),
      })
    )
    .min(1),
};

export const batchCreateFunctionalCasesTool = {
  name: "batch_create_functional_cases",
  description: "Batch import agent-generated functional cases into a project/module.",
  inputSchema: batchCreateFunctionalCasesInputSchema,
  handler: async (client: MeterSphereClient, args: Record<string, unknown>) => {
    const result = await client.batchCreateFunctionalCases(
      args as Parameters<MeterSphereClient["batchCreateFunctionalCases"]>[0]
    );
    return { content: [{ type: "text" as const, text: JSON.stringify(result, null, 2) }] };
  },
};
